### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shubhamjanhere** [Kurt7799/SVM-on-dataset-Titanic#1]
In the 30th line of code, you have written -
`fit.svm<-svm(Survived~.,data=extractFeatures(train))
`
Instead, it should be - 
`fit.svm<-svm(train$Survived~.,data=extractFeatures(train))
`
Please correct it. Or else it will give error. 
Thanks/

**Comment by Kurt7799** [comment]
Thank you very much 
I will correct it ASAP

**Comment by Kurt7799** [comment]
sorry i'm new to github 
i don't know whether my operation is right or not 
any advice is  appreciated 
just email me willchiu7799@outlook.com

**Comment by Kurt7799** [comment]
this error has been fixed
thanks to shubhamjanhere
